//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Reflection;
using robotlegs.bender.framework.api;
using System.Collections.Generic;


namespace robotlegs.bender.framework.impl
{
	public class Guards
	{
		public static bool Approve(IInjector injector, IEnumerable<object> guards)
		{
			object guardInstance;

			foreach (object guard in guards)
			{
				if (guard is Func<bool>)
				{
					if ((guard as Func<bool>)())
						continue;
					return false;
				}
				if (guard is Type)
				{
					if (injector != null)
						guardInstance = injector.InstantiateUnmapped(guard as Type);
					else
						guardInstance = Activator.CreateInstance(guard as Type);
				}
				else
					guardInstance = guard;

				MethodInfo approveMethod = guardInstance.GetType().GetMethod("Approve");
				if (approveMethod != null)
				{
					if ((bool)approveMethod.Invoke (guardInstance, null) == false)
						return false;
				}
				else
				{
					throw(new Exception (String.Format("Guard {0} is not a valid guard. It doesn't have the method 'Approve'", guardInstance)));
				}
			}
			return true;
		}

		public static bool Approve(IInjector injector, params object[] guards)
		{
			return Approve (injector, guards as IEnumerable<object>);
		}

		public static bool Approve(params object[] guards)
		{
			return Approve (null, guards as IEnumerable<object>);
		}

		public static bool Approve(IEnumerable<object> guards)
		{
			return Approve (null, guards);
		}

		public static bool Approve(params Func<bool>[] guards)
		{
			return Approve (null, guards as IEnumerable<object>);
		}

		public static bool Approve(IInjector injector, params Func<bool>[] guards)
		{
			return Approve (injector, guards as IEnumerable<object>);
		}

		public static bool Approve(IInjector injector, IEnumerable<Func<bool>> guards)
		{
			return Approve (injector, guards as IEnumerable<object>);
		}
	}
}

