//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using strange.context.api;
using System.Collections.Generic;


namespace robotlegs.bender.framework.impl
{
	/// <summary>
	/// The object processor, the core for Config Manager.
	/// It takes adds IMatchers which checks if you can process the object with your handler function
	/// </summary>

	public class ObjectProcessor
	{
		private List<ObjectHandler> _handlers = new List<ObjectHandler>();

		public void AddObjectHandler (IMatcher matcher, Action<object> handler)
		{
			_handlers.Add(new ObjectHandler(matcher, handler));
		}

		public void ProcessObject(object obj)
		{
			foreach (ObjectHandler handler in _handlers)
			{
				handler.Handle(obj);
			}
		}

		public void RemoveAllHandlers()
		{
			_handlers.Clear();
		}
	}

	/// <summary>
	/// Object handler
	/// A single instance of checking a IMatcher and then processing your handler function
	/// </summary>

	public class ObjectHandler
	{
		private IMatcher _matcher;
		private Action<object> _handler;

		public ObjectHandler(IMatcher matcher, Action<object> handler)
		{
			_handler = handler;
			_matcher = matcher;
		}
		
		public void Handle(object obj)
		{
			if (_matcher.Matches(obj))
				_handler(obj);
		}
	}
}

