//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using robotlegs.bender.extensions.viewManager;
using UnityEngine;


namespace strange.unity
{
	public class UnityParentFinder : IParentFinder
	{
		public object FindParentContainer(object view, object[] containers)
		{
			if (view is Component)
				view = (view as Component).transform;
			if (view is GameObject)
				view = (view as GameObject).transform;
			if (view is Transform)
			{
				Transform currentTransform = view as Transform;
				while (currentTransform.parent != null)
				{
					foreach (Component component in currentTransform.GetComponentsInChildren<Component>())
					{
						foreach (object container in containers)
						{
							if (container == component)
								return container;
						}
					}
					currentTransform = currentTransform.parent;
				}
			}

			return null;
		}
	}
}

