//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using swiftsuspenders.mapping;

namespace robotlegs.bender.platforms.unity.extensions.unitySingletons.impl
{
	public class UnitySingletons : MonoBehaviour
	{
		/*============================================================================*/
		/* Public Properties                                                          */
		/*============================================================================*/
		
		public event Action<MappingId, object> AddedSingleton;
		
		public event Action<MappingId> RemovedSingleton;

		public SingletonFactory Factory
		{
			get
			{
				return _factory;
			}
		}

		/*============================================================================*/
		/* Private Properties                                                         */
		/*============================================================================*/

		private SingletonFactory _factory;
		
		/*============================================================================*/
		/* Constructor                                                                */
		/*============================================================================*/

		public void SetFactory(SingletonFactory factory)
		{
			if (_factory != null) 
			{
				_factory.AddedSingleton -= OnAddedSingleton;
				_factory.RemovedSingleton -= OnRemovedSingleton;
			}

			_factory = factory;
		}
		
		/*============================================================================*/
		/* Private Functions                                                          */
		/*============================================================================*/

		private void OnAddedSingleton(MappingId mappingId, object singleton)
		{
			if (AddedSingleton != null) 
			{
				AddedSingleton (mappingId, singleton);
			}
		}

		private void OnRemovedSingleton(MappingId mappingId)
		{
			if (RemovedSingleton != null) 
			{
				RemovedSingleton (mappingId);
			}
		}
	}
}
