//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using UnityEditor;
using UnityEngine;
using System;
using System.Collections.Generic;
using robotlegs.bender.platforms.unity.extensions.monoscriptCache.api;

namespace robotlegs.bender.platforms.unity.extensions.unityMediatorManager.impl
{
	[CustomEditor(typeof(MediatorAttach))]
	public class MediatorAttachEditor : Editor
	{
		/*============================================================================*/
		/* Private Properties                                                         */
		/*============================================================================*/

		private bool start;

		private MediatorAttach mediatorAttach;

		/*============================================================================*/
		/* Private Functions                                                          */
		/*============================================================================*/

		private void OnEnable()
		{
			if (start)
				return;

			start = true;

			mediatorAttach = target as MediatorAttach;
		}
		
		/*============================================================================*/
		/* Public Functions                                                           */
		/*============================================================================*/

		public override void OnInspectorGUI()
		{
			EditorGUILayout.LabelField ("View", mediatorAttach.View.GetType().Name);
			foreach (object mediator in mediatorAttach.Mediators) 
			{
				MonoScript ms = MonoScriptCache.GetMonoScript(mediator.GetType());
				if (ms != null)
				{
					EditorGUILayout.ObjectField("Mediator", ms, typeof(MonoScript), false);
				}
				else
				{
					EditorGUILayout.LabelField ("Mediator", mediator.GetType().Name);
				}
			}
		}
	}
}

