//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using robotlegs.bender.extensions.mediatorMap.impl;
using System.Reflection;
using robotlegs.bender.extensions.mediatorMap.api;
using UnityEngine;
using System.Collections.Generic;
using robotlegs.bender.extensions.mediatorMap.dsl;


namespace robotlegs.bender.platforms.unity.extensions.unityMediatorManager.impl
{
	public class UnityMediatorManager : IMediatorManager
	{
		/*============================================================================*/
		/* Public Properties                                                          */
		/*============================================================================*/
		
		public event Action<object> ViewRemoved;

		/*============================================================================*/
		/* Private Properties                                                         */
		/*============================================================================*/

		private Dictionary<object, MediatorAttach> _viewMediatorAttachDictionary = new Dictionary<object, MediatorAttach> ();

		/*============================================================================*/
		/* Public Functions                                                           */
		/*============================================================================*/
		
		public void AddMediator(object mediator, object item, IMediatorMapping mapping)
		{
			if (item is IView && mapping.AutoRemoveEnabled)
			{
				(item as IView).RemoveView += HandleRemoveView;
			}
			
			InitializeMediator(mediator, item);

			AddMediatorAttach (mediator, item);
		}
		
		public void RemoveMediator(object mediator, object item, IMediatorMapping mapping)
		{
			if (item is IView)
			{
				(item as IView).RemoveView -= HandleRemoveView;
			}

			RemoveMediatorAttach (mediator, item);

			DestroyMediator(mediator);
		}
		
		/*============================================================================*/
		/* Private Functions                                                          */
		/*============================================================================*/

		private void AddMediatorAttach(object mediator, object view)
		{
			if (view is Component) 
			{
				MediatorAttach mediatorAttach;
				if (!_viewMediatorAttachDictionary.ContainsKey(view))
				{
					mediatorAttach = (view as Component).gameObject.AddComponent<MediatorAttach>();
					mediatorAttach.SetView(view);
					_viewMediatorAttachDictionary.Add(view, mediatorAttach);
				}
				else
				{
					mediatorAttach = _viewMediatorAttachDictionary[view];
				}
				mediatorAttach.AddMediator(mediator);
			}
		}

		private void RemoveMediatorAttach(object mediator, object view)
		{
			if (!_viewMediatorAttachDictionary.ContainsKey (view)) 
				return;
			
			MediatorAttach mediatorAttach = _viewMediatorAttachDictionary[view];
			mediatorAttach.RemoveMediator (mediator);

			if (mediatorAttach.Mediators.Length == 0) 
			{
				GameObject.Destroy (mediatorAttach);
				_viewMediatorAttachDictionary.Remove (view);
			}
		}
		
		private void HandleRemoveView (IView view)
		{
			if (ViewRemoved != null) 
			{
				ViewRemoved (view);
			}
		}
		
		private void InitializeMediator(object mediator, object mediatedItem)
		{
			Type mediatorType = mediator.GetType();
			
			CallMethod("PreInitialize", mediatorType, mediator);
			SetFieldOrProperty("viewComponent", mediatorType, mediator, mediatedItem);
			CallMethod("Initialize", mediatorType, mediator);
			CallMethod("PostInitialize", mediatorType, mediator);
		}
		
		private void DestroyMediator(object mediator)
		{
			Type mediatorType = mediator.GetType();
			
			CallMethod("PreDestroy", mediatorType, mediator);
			CallMethod("Destroy", mediatorType, mediator);
			SetFieldOrProperty("viewComponent", mediatorType, mediator, null);
			CallMethod("PostDestroy", mediatorType, mediator);
		}
		
		private bool CallMethod(string methodName, Type mediatorType, object instance)
		{
			MethodInfo methodInfo = mediatorType.GetMethod(methodName);
			if (methodInfo == null)
				return false;
			
			methodInfo.Invoke(instance, null);
			return true;
		}
		
		private object SetFieldOrProperty(string fieldName, Type mediatorType, object instance, object fieldValue)
		{
			FieldInfo fieldInfo = mediatorType.GetField(fieldName);
			if (fieldInfo == null)
			{
				PropertyInfo propertyInfo = mediatorType.GetProperty (fieldName);
				if (propertyInfo == null)
					return false;
				else
				{
					propertyInfo.SetValue (instance, fieldValue, null);
				}
			}
			else
			{
				fieldInfo.SetValue (instance, fieldValue);
			}
			return true;
		}
	}
}
