//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using robotlegs.bender.extensions.eventDispatcher.api;
using robotlegs.bender.extensions.mediatorMap.api;


namespace strange.extensions.mediation.impl
{
	public interface IEventView : IView
	{
		IEventDispatcher dispatcher{ get; set;}
	}
}
