//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using UnityEditor;
using UnityEngine;


namespace robotlegs.bender.platforms.unity.extensions.monoscriptCache
{
	public static class MonoScriptCache
	{
		/*============================================================================*/
		/* Private Static Properties                                                  */
		/*============================================================================*/

		private static Dictionary<Type, MonoScript> monoScriptsCache;
		
		/*============================================================================*/
		/* Public Static Functions                                                    */
		/*============================================================================*/

		public static MonoScript GetMonoScript(Type type)
		{
			if (monoScriptsCache == null) 
			{
				GetMonoscriptCache ();
			}

			MonoScript monoScript;
			monoScriptsCache.TryGetValue (type, out monoScript);
			return monoScript;
		}
		
		/*============================================================================*/
		/* Private Static Functions                                                   */
		/*============================================================================*/

		private static void GetMonoscriptCache()
		{
			monoScriptsCache = new Dictionary<Type, MonoScript> ();

			MonoScript[] monoScripts = Resources.FindObjectsOfTypeAll<MonoScript>();
			foreach (MonoScript monoScript in monoScripts) 
			{
				Type monoScriptType = monoScript.GetClass();
				if (monoScriptType == null)
					continue;

				monoScriptsCache[monoScriptType] = monoScript;
			}
		}
	}
}

