//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using robotlegs.bender.extensions.mediatorMap.api;


namespace robotlegs.bender.extensions.mediatorMap.dsl
{
	public interface IMediatorFactory
	{
		object GetMediator (object item, IMediatorMapping mapping);
		
		List<object> CreateMediators (object item, Type type, IEnumerable<IMediatorMapping> mappings);
		
		void RemoveMediators (object item);
		
		void RemoveAllMediators();
	}
}

