//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using robotlegs.bender.extensions.mediatorMap.api;

namespace robotlegs.bender.extensions.mediatorMap.dsl
{
	public interface IMediatorManager
	{
		event Action<object> ViewRemoved;

		void AddMediator (object mediator, object item, IMediatorMapping mapping);

		void RemoveMediator (object mediator, object item, IMediatorMapping mapping);
	}
}