//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace robotlegs.bender.extensions.mediatorMap.dsl
{
	/// <summary>
	/// Unmaps a Mediator
	/// </summary>
	public interface IMediatorUnmapper
	{
		/// <summary>
		/// Unmaps a mediator from this matcher
		/// </summary>
		/// <param name="mediatorType">Mediator to unmap</param>
		void FromMediator(Type mediatorType);

		/// <summary>
		/// Unmaps all mediator mappings for this matcher
		/// </summary>
		void FromAll();
	}
}

