//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using robotlegs.bender.framework.api;
using robotlegs.bender.extensions.viewManager.impl;
using robotlegs.bender.framework.unity.extensions.viewManager.impl;
using robotlegs.bender.extensions.viewManager;


namespace robotlegs.bender.platforms.unity.extensions.viewManager
{
	public class UnityParentFinderExtension : IExtension
	{
		private IInjector _injector;

		private IParentFinder _parentFinder;

		public void Extend (IContext context)
		{
			_injector = context.injector;

			_parentFinder = new UnityParentFinder();
			_injector.Map(typeof(IParentFinder)).ToValue(_parentFinder);
			context.BeforeInitializing(BeforeInitializing);
		}

		private void BeforeInitializing()
		{
			ContainerRegistry registry = _injector.GetInstance(typeof(ContainerRegistry)) as ContainerRegistry;
			registry.SetParentFinder(_parentFinder);
		}
	}
}