//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using robotlegs.bender.framework.api;
using robotlegs.bender.unity.extensions.debugLogging;
using robotlegs.bender.extensions.vigilance;
using robotlegs.bender.extensions.enhancedLogging;
using robotlegs.bender.extensions.contextview;
using robotlegs.bender.extensions.eventDispatcher;
using robotlegs.bender.extensions.directCommandMap;
using robotlegs.bender.extensions.eventCommandMap;
using robotlegs.bender.extensions.localEventMap;
using robotlegs.bender.extensions.viewManager;
using robotlegs.bender.extensions.mediatorMap;
using robotlegs.bender.framework.impl;
using robotlegs.bender.unity.extensions.contextview;
using robotlegs.bender.unity.extensions.viewManager;
using robotlegs.bender.unity.extensions.viewManager.impl;
using robotlegs.bender.extensions.modularity;
using robotlegs.bender.extensions.viewProcessorMap;

namespace robotlegs.bender.bundles
{
	public class UnityMVCSBundle : IExtension
	{
		public void Extend (IContext context)
		{
			context.LogLevel = LogLevel.INFO;
			
			context.Install(typeof(DebugLoggingExtension));
			context.Install(typeof(VigilanceExtension));
			context.Install(typeof(InjectableLoggerExtension));
			context.Install(typeof(UnityParentFinderExtension));
			context.Install(typeof(ContextViewExtension));
			context.Install(typeof(EventDispatcherExtension));
			context.Install(typeof(ModularityExtension));
			context.Install(typeof(DirectCommandMapExtension));
			context.Install(typeof(EventCommandMapExtension));
			context.Install(typeof(LocalEventMapExtension));
			context.Install(typeof(ViewManagerExtension));
			context.Install(typeof(MediatorMapExtension));
			context.Install(typeof(ViewProcessorMapExtension));
			context.Install(typeof(StageCrawlerExtension));
			context.Install(typeof(StageSyncExtension));
			context.Install(typeof(UnityViewStateWatcherExtension));


			context.Configure(typeof(UnityStageCrawlerConfig));
			context.Configure(typeof(ContextViewListenerConfig));
		}
	}
}

