//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using robotlegs.bender.extensions.viewManager.impl;
using UnityEngine;
using robotlegs.bender.extensions.mediatorMap.api;

namespace robotlegs.bender.platforms.unity.extensions.viewManager.impl
{
	public class UnityFallbackStageCrawler : StageCrawler
	{
		protected override void ScanContainer (object container)
		{
			ScanAll ();
		}
		
		private void ProcessViewsFromRoot(Transform view)
		{
			ScanAll ();
		}

		private void ScanAll()
		{
			object[] viewScripts = GameObject.FindObjectsOfType(typeof(MonoBehaviour));
			
			foreach (MonoBehaviour viewScript in viewScripts)
			{
				if (viewScript is IView)
				{
					ProcessView (viewScript);
				}
			}
		}
	}
}