//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using robotlegs.bender.extensions.viewManager.impl;

namespace robotlegs.bender.extensions.viewManager
{
	public interface IParentFinder
	{
		/// <summary>
		/// Method to check if a container contains another container
		/// </summary>
		/// <param name="container">The parent container</param>
		/// <param name="obj">The child container</param>
		bool Contains (object parentContainer, object childContainer);

		// View Find Parent Container
		/// <summary>
		/// Method to check the view to find it's container (if any)
		/// </summary>
		/// <returns>The parent container object or null</returns>
		/// <param name="child">The child view</param>
		/// <param name="containers">A dictionary of ContainerBindings by Container as a key</param>
		object FindParent (object childView, Dictionary<object, ContainerBinding> containers);
		object FindParent (object childView, List<ContainerBinding> containers);
	}
}