//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace robotlegs.bender.extensions.mediatorMap.api
{
	public interface IMediator
	{
		/**
		 * Initializes the mediator. This is run automatically by the mediatorMap when a mediator is created.
		 * Normally the initialize function is where you would add handlers using the eventMap.
		 */
		void Initialize();
		
		/**
		 * Destroys the mediator. This is run automatically by the mediatorMap when a mediator is destroyed.
		 * You should clean up any handlers that were added directly (eventMap handlers will be cleaned up automatically).
		 */
		void Destroy();
	}
}

