//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using robotlegs.bender.extensions.matching;
using System.Collections.Generic;


namespace robotlegs.bender.extensions.mediatorMap.api
{
	public interface IMediatorMapping
	{
		/// <summary>
		/// The matcher for this mapping
		/// </summary>
		/// <value>The matcher for this mapping</value>
		ITypeFilter Matcher {get;}

		/// <summary>
		/// The concrete mediator class
		/// </summary>
		/// <value>The concrete mediator class</value>
		Type MediatorType {get;}

		/// <summary>
		/// A list of guards to check before allowing mediator creation
		/// </summary>
		/// <value>A list of guards to check before allowing mediator creation</value>
		List<object> Guards {get;}

		/// <summary>
		/// A list of hooks to run before creating a mediator
		/// </summary>
		/// <value>A list of hooks to run before creating a mediator</value>
		List<object> Hooks {get;}

		/// <summary>
		/// Should the mediator be removed when the mediated item looses scope?
		/// </summary>
		/// <value>Should the mediator be removed when the mediated item looses scope?</value>
		bool AutoRemoveEnabled {get;}
	}
}

