//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class UnitySingletons : MonoBehaviour
{
	/*============================================================================*/
	/* Public Properties                                                          */
	/*============================================================================*/

	public SingletonFactory Factory
	{
		get
		{
			return _factory;
		}
	}

	/*============================================================================*/
	/* Private Properties                                                         */
	/*============================================================================*/

	private SingletonFactory _factory;
	
	/*============================================================================*/
	/* Constructor                                                                */
	/*============================================================================*/

	public void SetFactory(SingletonFactory factory)
	{
		_factory = factory;
	}
}

