//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEditor;
using System.Collections.Generic;
using swiftsuspenders.mapping;

[CustomEditor(typeof(UnitySingletons))]
public class UnitySingletonsEditor : Editor
{
	public override void OnInspectorGUI ()
	{
		UnitySingletons unitySingletons = target as UnitySingletons;
		foreach (KeyValuePair<MappingId, object> kvp in unitySingletons.Factory.SingletonInstances) 
		{
			string label = kvp.Key.type.Name;
			if (kvp.Key.key != null)
				label += ": " + kvp.Key.key.ToString();
			EditorGUILayout.LabelField(label, kvp.Value.GetType().Name);
		}
	}
}
