//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using robotlegs.bender.framework.impl;


namespace robotlegs.bender.framework.api
{
	public interface ILogTarget
	{
		/// <summary>
		/// Captures a log message
		/// </summary>
		/// <param name="source">The source of the log message</param>
		/// <param name="level">The log level of the message</param>
		/// <param name="timestamp">message timestamp</param>
		/// <param name="message">The log message</param>
		/// <param name="messageParameters">Message parameters</param>
		void Log(object source, LogLevel level, DateTime timestamp, object message, params object[] messageParameters);
	}
}

