//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using robotlegs.bender.extensions.contextview.api;
using UnityEngine;


namespace robotlegs.bender.platforms.unity.extensions.contextview.impl
{
	public class TransformContextView : IContextView
	{
		/*============================================================================*/
		/* Public Properties                                                          */
		/*============================================================================*/

		public object view
		{
			get 
			{
				return _transform;
			}
		}
		
		public Transform transform
		{
			get
			{
				return _transform;
			}
		}

		/*============================================================================*/
		/* Private Properties                                                         */
		/*============================================================================*/
		
		private Transform _transform;

		/*============================================================================*/
		/* Public Functions                                                           */
		/*============================================================================*/

		public TransformContextView (Transform view)
		{
			_transform = view;
		}
	}
}

